config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :jobs
  root 'pages#home'

  get 'pages/about'
  get 'pages/places'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    # Anonymous user abilities
    can :read, Job
    can :new, Job
    
    # Signed in user abilities
    if user.persisted?
      can :create, Job
    end

    # Users that own a Job
    can :edit, Job do |job|
      job.try(:user) == user
    end

    can :update, Job do |job|
      job.try(:user) == user
    end

    can :destroy, Job do |job|
      job.try(:user) == user
    end

    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search,
                :against => [:title, :location, :description, :company, :url,:email, :category_id],
                :using => {
                  :tsearch => {:dictionary => "english"}
                }

  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs

  include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
  	@jobs = Job.all.order("created_at DESC")
  end

  def show
  end

  def new

    # Make sure that a user session is active before creating a job.
    unless user_signed_in?
      store_location_for(:user, new_job_path)
      redirect_to new_user_session_path
    end

    @job = Job.new
  end

  def create
    @job.user = current_user

    if @job.save
      redirect_to @job
    else
      render "New"
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render "Edit"
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :location, :description, :company, :url,
                                :email, :category_id)
  end

  def find_job
  	@job = Job.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def places
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Evaluates to true if the request is for the "homepage"
  def homepage?
    request.original_fullpath == "/"
  end

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.haml
%section#post
  .row
    .large-12.columns
      %h1
        Submit a Job

  .row
    .large-8.columns
      .section-container.tabs
        %section.section
          .content
            = simple_form_for(@job, html: {class: 'form-horizontal'}) do |f|
              // = f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"}
              .row.collapse
                .large-3.columns
                  %label.inline Job Title
                .large-9.columns
                  = f.input :title, placeholder: 'Developer, Designer', label: false 
              .row.collapse
                .large-3.columns 
                  %label.inline Job Location
                .large-9.columns    
                  = f.input :location, placeholder: "Example: 'Chattanooga', 'Remote' ", label: false 
              .row.collapse
                .large-3.columns
                  %label.inline Description
                .large-9.columns  
                  = f.input :description, rows: "20", label: false, placeholder: 'add some markdown for lists, headers, etc.'
              .row.collapse
                .large-3.columns
                  %label.inline Company Name
                .large-9.columns  
                  = f.input :company, label: false
              .row.collapse
                .large-3.columns
                  %label.inline Company URL
                .large-9.columns 
                  = f.input :url, label: false 
              .row.collapse
                .large-3.columns
                  %label.inline Apply URL
                .large-9.columns    
                  = f.input :email, placeholder: 'user@domain.com', label: false 

              = f.button :submit, :class => "a button left"

            

      %a{href: "/pages/jobs"} Back to job board


    .large-4.columns
      .panel
        %h3 Why post a job?
        %br/
        %p Nooga startups is a  Job Board, by the community for the community.

        %p When you post on this board, your job post is tweeted to the Nooga Startups twitter account and will be put in the job section of the Nooga startups website for one month.

        %p Nooga Startups is the best resource to fill your positions with motivated and passionate developers and designers who love their craft.

app/views/jobs/edit.html.haml
.row
  .large-8.columns
    .alert-box.radius
      Editing your job post...
= render 'form'

app/views/jobs/index.html.haml
%section#jobs
  .row
    .large-12.columns
      %h1
        Jobs
  .row
    .large-8.columns
      .row.collapse
        / Commenting out for now. Submit a pull request for this issue! https://github.com/Tgemayel/Nooga-Startups/issues/34
        / .small-10.columns
        /   %input{placeholder: "Search jobs, companies, or locations...", type: "text"}/
        / .small-2.columns
        /   %a.button.postfix{href: "#"} Go
      .row
        .small-12.columns
          %table
            %thead
              %tr
                %th{width: "300"} Description
                %th{width: "200"} Company
                %th{width: "150"} Date
            %tbody
              - @jobs.each do |job|
                %tr
                  %td= link_to job.title, job
                  %td= job.company
                  // %td date posted 
                  %td= job.created_at.strftime("%b. %d")



    .large-4.columns
      %a.button{href: "/jobs/new"} Submit a job
      %p
        Nooga Startups is a job board, open sourced for developers and designers.
      %p
        Find a position at a startup with motivated and passionate developers and designers who love their craft.
      %p
        Questions or comments please contact us
        %a{href: "#@lamppostgroup.com?subject=Nooga Startups Job Board"}here.

app/views/jobs/new.html.haml
= render 'form'

app/views/jobs/show.html.haml
%section#page
  .row
    .large-12.columns
      %h1 Job Post
    - if user_signed_in?
      = link_to "Home", root_path
      = link_to "Edit", edit_job_path(@job)
      = link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure you want to delete this job?" }
    - else  

  .row
    .large-10.columns{role: "content"}
      %h3= @job.title
      .row
        .large-10.columns
          %h4.location
            = @job.company
      .row
        .large-10.columns
          %p
            Posted: June 12, 2014
          %hr
  .row
    .large-10.columns.job-post{role: "content"}
      %h3
        Job Description:
      .row
        .large-10.columns
          %p
            = markdown_to_html @job.description

  .row
    .large-10.columns{role: "content"}
      %h3
        How to apply:
      .row
        .large-10.columns
          %p
            Please send a short note introducing yourself and why this position appeals to you. Include a resume, and links to code samples and a link to a portfolio if you have one.
          %p
            Applicants must be authorized to work in the United States.

          .button.mail-to
            = mail_to @job.email, "Apply to this job"

          %a.button{href: "/jobs"} Back to job board

app/views/layouts/_footer.html.haml
%footer
  .row
    .large-12.columns
      - unless homepage?
        %hr
      .row
        .large-8.columns
          %p
            Created by
            %a{:href => "https://twitter.com/tonigemayel"}Toni,
            %a{:href => "https://twitter.com/tjweigel"}TJ,
            %a{:href => "http://fancyrhino.com/"}Fancy,
            and our awesome
            %a{:href => "https://github.com/Tgemayel/Nooga-Startups/graphs/contributors"} community.
        .large-4.columns

app/views/layouts/_header.html.haml
.row
  .text-center.small-12.medium-2.large-1.columns
    %h2
      %a{href: "/"} N
  .small-12.medium-10.large-11.columns
    %ul.inline-list
      %li= link_to "About", pages_about_path
      %li= link_to "Jobs", jobs_path
      %li= link_to "Places", pages_places_path
      %li
        %a{:href => "https://twitter.com/noogastartups"}Twitter
      %li= link_to "Sign Up", new_user_registration_path
      - if user_signed_in?
        %li
          %a{href: "/users/edit"} |
            = image_tag current_user.gravatar_url(:size => 30)
      - else
        %li

app/views/layouts/_messages.html.haml
.row 
  .large-12.columns
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{class: "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
          = content_tag :div, msg
          %a.close{href: "#"} &#215;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Nooga Startups"
    %meta{content: content_for?(:description) ? yield(:description) : "Nooga Startups", name: "description"}/
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{src: "//use.typekit.net/lhq0hfv.js", type: "text/javascript"}
    :javascript
      try{Typekit.load();}catch(e){}

  %body
    %header= render 'layouts/header'
    = render 'layouts/messages'
    = yield
    = render 'layouts/footer'

app/views/pages/about.html.haml
%section#page
  .row
    .large-12.columns
      %h1
        About Us
  .row
    .large-10.columns{role: "content"}
      %h3
        What is Nooga Startups?
      .row
        .large-10.columns
          %p
            Nooga Startups is a directory of the awesome startups located in Chattanooga, Tennessee and was inspired by
            %a{href: "http://wearemadeinny.com/"}Made in New York.
  .row
    .large-10.columns{role: "content"}
      %h3
        Chatta-what?
      .row
        .large-10.columns
          %p
            Chattanooga fondly known as the 'Noog, 'Nooga, or simply "The Paris of Southeast." Chattanooga is home to a number of great startups, a fantastic outdoor scene, delicious food, and some great whiskey.
  .row
    .large-10.columns{role: "content"}
      %h3
        Interesting facts about Chattanooga:
      .row
        .large-10.columns
          %ul
            %li The world's first coca-cola bottling plant opened here in 1899.
            %li The annual Riverbend Music Festival is consistently rated as one of the best festivals in the country.
            %li World-class kayaking and climbing is located within thirty minutes of the city.
            %li The country's first 1gb/s residential network, and the coverage stretches across the entire county.
            %li Conveniently located ninety minutes from Atlanta, Nashville, Birmingham, and Knoxville. From country music concerts to the world's busiest international airport... it's all close.
  .row
    .large-10.columns{role: "content"}
      %h3
        What's the point?
      .row
        .large-10.columns
          %p
            It's time to get the secret out... Chattanooga has an emerging tech scene, a thriving downtown, and a lot of energy and momentum. We want to make it easier for engineers, journalists & founders to see whats happening in Chattanooga and get more information about the movement.
          %p
            Software is eating the world and the most successful economies of tomorrow are building around this. Our goal is for Chattanooga to be one of these economies and it's time to build the buzz and bring in the talent.
  .row
    .large-10.columns{role: "content"}
      %h3
        How can I get my startup on the list?
      .row
        .large-10.columns
          %p
            The easieszt way is to submit a
            %a{href: "https://github.com/Tgemayel/Nooga-Startups/pulls"}pull request
            or tweet us
            %a{href: "https://twitter.com/NoogaStartups"}@NoogaStartups
            if you need help.
          %p
            When submitting your pull request, make sure your image is 600x400 to keep all images consistent in size.
          %p
            Please note that at this time we are only looking for product-focused tech startups featuring a website our users can visit to learn more.
  .row
    .large-10.columns{role: "content"}
      %h3
        New to Github?
      .row
        .large-10.columns
          %p
            Please reference our
            %a{href: "https://github.com/Tgemayel/Nooga-Startups/blob/master/Readme.md#how-can-i-get-my-startup-added-to-this-list"}readme
            to get started.
  .row
    .large-10.columns{role: "content"}
      %h3
        I want to get involved
      .row
        .large-10.columns
          %p
            Great! We fully intend on this being a community run project. Check the
            %a{href: "https://github.com/Tgemayel/Nooga-Startups/issues"}issues log
            to see what things you can tackle first!

app/views/pages/home.html.haml
%section#hero
  .show-for-medium-up
    %video#bgvid{:autoplay => "", :loop => ""}
      %source{:src => "https://s3.amazonaws.com/Nooga-Startups/CHA_2.m4v", :type => "video/mp4"}
  .show-for-small-only
    #bgsmall
  .row
    .small-12.medium-9.small-centered.column
      %h1 Nooga Startups
      %h3.show-for-medium-up A showcase of internet companies and startups founded right here in Chattanooga, TN
      %a.button{:href => "/jobs"} Find A Job

%section#startups
  .row
    .text-center.small-12.column
      .row
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://ambition.com", :target => "_blank"}
            =image_tag("ambition.png", alt: "Office productivity with a purpose", title: "Ambition")
            %h2.large-only-text-left Ambition
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://americanexchange.com", :target => "_blank"}
            =image_tag("american.png", alt: "Health coverage for all", title: "American Exchange")
            %h2.large-only-text-left American Exchange
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://audiencepoint.com/", :target => "_blank"}
            =image_tag("audience.png", alt: "Send time optimization", title: "Audience Point")
            %h2.large-only-text-left Audience Point
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://getbellhops.com", :target => "_blank"}
            =image_tag("bellhops.png", alt: "Get college students for moving help", title: "Bellhops")
            %h2.large-only-text-left Bellhops
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://causeway.org", :target => "_blank"}
            =image_tag("causeway.png", alt: "Where there's a cause, there's a way", title: "Causeway")
            %h2.large-only-text-left Causeway
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://colab.co", :target => "_blank"}
            =image_tag("colab.png", alt: "From idea to business", title: "CoLab")
            %h2.large-only-text-left Company Lab
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://delegator.com", :target => "_blank"}
            =image_tag("delegator.png", alt: "Get it done", title: "Delegator")
            %h2.large-only-text-left Delegator
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://fancyrhino.com", :target => "_blank"}
            =image_tag("fancy.png", alt: "We are animal", title: "Fancy Rhino")
            %h2.large-only-text-left Fancy Rhino
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://fanjam.com", :target => "_blank"}
            =image_tag("fanjam.png", alt: "One-day fantasy basketball for cash", title: "FanJam")
            %h2.large-only-text-left FanJam
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://feetz.com", :target => "_blank"}
            =image_tag("feetz.png", alt: "Custom fit, 3D printed shoes made for you", title: "Feetz")
            %h2.large-only-text-left Feetz
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://lamppostgroup.com", :target => "_blank"}
            =image_tag("lpg.png", alt: "Pursue your passion, build your business", title: "Lamp Post Group")
            %h2.large-only-text-left Lamp Post Group
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://nooga.com", :target => "_blank"}
            =image_tag("nooga.png", alt: "Chattanooga news, entertainment, opinion, editorials.", title: "Nooga News")
            %h2.large-only-text-left Nooga.com
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://pricewaiter.com", :target => "_blank"}
            =image_tag("pricewaiter.png", alt: "Making free markets freer", title: "PriceWaiter")
            %h2.large-only-text-left PriceWaiter
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://quickcue.com", :target => "_blank"}
            =image_tag("quickcue.png", alt: "The smarter way to host your guests", title: "Quickcue")
            %h2.large-only-text-left Quickcue
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://reliancepartners.com", :target => "_blank"}
            =image_tag("reliance.png", alt: "Your trusted insurance providor", title: "Reliance Partners")
            %h2.large-only-text-left Reliance Partners
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://rootsrated.com", :target => "_blank"}
            =image_tag("rootsrated.png", alt: "Where to Go Outdoors", title: "RootsRated")
            %h2.large-only-text-left RootsRated
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://smartfurniture.com", :target => "_blank"}
            =image_tag("smart.png", alt: "Design your way", title: "Smart Furniture")
            %h2.large-only-text-left SmartFurniture
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://societyofwork.com", :target => "_blank"}
            =image_tag("sow.png", alt: "Connect. Create. Cowork.", title: "Societ of Work")
            %h2.large-only-text-left Society of Work
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://southtree.com", :target => "_blank"}
            =image_tag("southtree.png", alt: "Memories matter, preserve yours", title: "Southtree")
            %h2.large-only-text-left Southtree
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://spire.me", :target => "_blank"}
            =image_tag("spire.png", alt: "Community you can count on", title: "Spire")
            %h2.large-only-text-left Spire
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://steamlogistics.com", :target => "_blank"}
            =image_tag("steam.png", alt: "A new force in international logistics", title: "Steam Logistics")
            %h2.large-only-text-left Steam Logistics
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://supplyhog.com", :target => "_blank"}
            =image_tag("supplyhog.png", alt: "Get. Ship. Done.", title: "SupplyHog")
            %h2.large-only-text-left SupplyHog
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://tacoapp.com", :target => "_blank"}
            =image_tag("taco.png", alt: "All Your Tasks. One Screen. From Asana to Zendesk.", title: "Taco")
            %h2.large-only-text-left Taco    
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://variableinc.com", :target => "_blank"}
            =image_tag("variable.png", alt: "We are a world of gadgeteers", title: "Variable Technologies")
            %h2.large-only-text-left Variable
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://waypaverlabs.corg", :target => "_blank"}
            =image_tag("waypaver.png", alt: "THE SKY'S NOT THE LIMIT.", title: "Waypaver Labs")
            %h2.large-only-text-left Waypaver Labs
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://wecounsel.com", :target => "_blank"}
            =image_tag("wecounsel.png", alt: "An online therapy innovation", title: "We Counsel")
            %h2.large-only-text-left WeCounsel
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://whiteboard.is", :target => "_blank"}
            =image_tag("whiteboard.png", alt: "We empower visionaries to lead meaningful brands.", title: "Whiteboard")
            %h2.large-only-text-left Whiteboard
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://woople.com", :target => "_blank"}
            =image_tag("woople.png", alt: "Simple eLearning for your organization", title: "Woople")
            %h2.large-only-text-left Woople
        .medium-6.large-4.columns
          %a.startups-entry{:href => "http://zipflip.com", :target => "_blank"}
            =image_tag("zipflip.png", alt: "Safer.Smarter.Simpler.", title: "Zipflip")
            %h2.large-only-text-left Zipflip

app/views/pages/places.html.haml
%section#page
  .row
    .large-12.columns
      %h1
        City Guide
  .row
    .large-10.columns{role: "content"}
      %h3
        Coffee Shops
      .row
        .large-10.columns
          %ul
            %li
              %a{href: "https://goo.gl/maps/BPgu7", :target => "_blank"} The Camphouse
            %li
              %a{href: "https://goo.gl/maps/BYnV6", :target => "_blank"} Rembrandt's Coffee House & Cafe
            %li
              %a{href: "https://goo.gl/maps/jY7bV", :target => "_blank"} Niedlov’s Bakery
            %li
              %a{href: "https://goo.gl/maps/5pyLe", :target => "_blank"} Mean Mug Coffeehouse
            %li
              %a{href: "https://goo.gl/maps/do8Xk", :target => "_blank"} Cadence Coffee
            %li
              %a{href: "https://goo.gl/maps/6lIuc", :target => "_blank"} Greyfriar’s Coffee & Tea Co.
            %li
              %a{href: "https://goo.gl/maps/0TOsf", :target => "_blank"} Brash Coffee
  .row
    .large-10.columns{role: "content"}
      %h3
        Food
      .row
        .large-10.columns
          %ul
            %li
              %a{href: "https://goo.gl/maps/rv32x", :target => "_blank"} The Terminal Brewhouse
            %li
              %a{href: "https://goo.gl/maps/BPgu7"} The Camphouse
            %li
              %a{href: "https://goo.gl/maps/hPQhO", :target => "_blank"} Urban Stack
            %li
              %a{href: "https://goo.gl/maps/u2iCN", :target => "_blank"} Community Pie
            %li
              %a{href: "https://goo.gl/maps/vpOBz", :target => "_blank"} Chattanooga Billiard Club
            %li
              %a{href: "https://goo.gl/maps/TYXSE", :target => "_blank"} Blue Water Grill
            %li
              %a{href: "https://goo.gl/maps/9Lld8", :target => "_blank"} Big River Grille
            %li
              %a{href: "https://goo.gl/maps/Q26Kx", :target => "_blank"} Taco Mamacita
            %li
              %a{href: "https://goo.gl/maps/IDNzL", :target => "_blank"} Lupi's Pizza
            %li
              %a{href: "https://goo.gl/maps/I3Lwx", :target => "_blank"} Blue Plate
            %li
              %a{href: "https://goo.gl/maps/jYlxF", :target => "_blank"} Public House
            %li
              %a{href: "https://goo.gl/maps/q187d", :target => "_blank"} Porkers
            %li
              %a{href: "https://goo.gl/maps/M1vuc", :target => "_blank"} Easy Bistro
            %li
              %a{href: "https://goo.gl/maps/VTIRv", :target => "_blank"} Sekisui
            %li
              %a{href: "https://goo.gl/maps/8e62T", :target => "_blank"} Genghis Grill
            %li
              %a{href: "https://goo.gl/maps/ppjgf", :target => "_blank"} Conga
            %li
              %a{href: "https://goo.gl/maps/ABB6a", :target => "_blank"} Tacqueria Jalisco
            %li
              %a{href: "https://goo.gl/maps/hWEmK", :target => "_blank"} Mojo Burrito
            %li
              %a{href: "https://goo.gl/maps/qUvZd", :target => "_blank"} La Altena
            %li
              %a{href: "https://goo.gl/maps/MoHdd", :target => "_blank"} Hair of the Dog
            %li
              %a{href: "https://goo.gl/maps/7QBjg", :target => "_blank"} Brewhaus
            %li
              %a{href: "https://goo.gl/maps/Ces84", :target => "_blank"} Tony's Pasta Shop & Trattoria
            %li
              %a{href: "https://goo.gl/maps/BYnV6", :target => "_blank"} Rembrandt's
            %li
              %a{href: "https://goo.gl/maps/fAMSx", :target => "_blank"} Beast + Barrel
            %li
              %a{href: "https://goo.gl/maps/NTqe7", :target => "_blank"} 212 Market
            %li
              %a{href: "https://goo.gl/maps/QZ26p", :target => "_blank"} Champy's
            %li
              %a{href: "https://goo.gl/maps/MDmd9", :target => "_blank"} Crust Pizza
            %li
              %a{href: "https://goo.gl/maps/irylW", :target => "_blank"} Mellow Mushroom
            %li
              %a{href: "https://goo.gl/maps/mLJvy", :target => "_blank"} Go Bagel
            %li
              %a{href: "https://goo.gl/maps/OQQSY", :target => "_blank"} Alleia
            %li
              %a{href: "https://goo.gl/maps/AJJMR", :target => "_blank"} Good Dog
            %li
              %a{href: "https://goo.gl/maps/EcfOM", :target => "_blank"} Hill City Pizza
            %li
              %a{href: "https://goo.gl/maps/Bzzr6", :target => "_blank"} Sticky Fingers
            %li
              %a{href: "https://goo.gl/maps/iPjmd", :target => "_blank"} Jimmy Johns
  .row
    .large-10.columns{role: "content"}
      %h3
        Bars
      .row
        .large-10.columns
          %ul
            %li
              %a{href: "https://goo.gl/maps/VGmFp", :target => "_blank"} The Social
            %li
              %a{href: "https://goo.gl/maps/9Lld8", :target => "_blank"} Big River Grille
            %li
              %a{href: "https://goo.gl/maps/3T0ak", :target => "_blank"} Tremont Tavern
            %li
              %a{href: "https://goo.gl/maps/EcfOM", :target => "_blank"} Hill City
            %li
              %a{href: "https://goo.gl/maps/fAMSx", :target => "_blank"} Beast + Barrel
            %li
              %a{href: "https://goo.gl/maps/u2iCN", :target => "_blank"} Community Pie
            %li
              %a{href: "https://goo.gl/maps/bdxMW", :target => "_blank"} Local 191
            %li
              %a{href: "https://goo.gl/maps/hPQhO", :target => "_blank"} Urban Stack
            %li
              %a{href: "https://goo.gl/maps/rv32x", :target => "_blank"} Terminal Brewhouse
            %li
              %a{href: "https://goo.gl/maps/7QBjg", :target => "_blank"} Brewhaus
            %li
              %a{href: "https://goo.gl/maps/MoHdd", :target => "_blank"} Hair of the Dog Pub
            %li
              %a{href: "https://goo.gl/maps/vpOBz", :target => "_blank"} Chattanooga Billiard Club
            %li
              %a{href: "https://goo.gl/maps/M1vuc", :target => "_blank"} Easy Bistro & Bar